<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.7" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.7" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.14" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bank.BL\Bank.BL.csproj" />
    <ProjectReference Include="..\Core.DAL\Core.DAL.csproj" />
    <ProjectReference Include="..\Core.DTO\Core.DTO.csproj" />
  </ItemGroup>

</Project>
