// <auto-generated />
using System;
using Core.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.DAL.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20250305123723_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.DAL.Models.BankAccounts.Tariff.CreditTariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double precision");

                    b.Property<decimal>("MinimumPayment")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ModifyDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CreditTariffs");
                });

            modelBuilder.Entity("Core.DAL.Models.Base.BaseBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character(200)")
                        .IsFixedLength();

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("BankAccountType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .IsFixedLength();

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifyDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("BankAccounts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Core.DAL.Models.Base.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardCategory")
                        .HasColumnType("integer");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CardType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifyDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cards");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Core.DAL.Models.History.BankAccountOperationsHistory", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OperationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BankAccountOperationInitiator")
                        .HasColumnType("integer");

                    b.Property<int>("BankAccountOperationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("BankAccountOperationType")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OperatingMoney")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("numeric");

                    b.HasKey("BankAccountId", "UserId", "OperationDateTime");

                    b.HasIndex("UserId");

                    b.ToTable("BankAccountOperationsHistory");
                });

            modelBuilder.Entity("Core.DAL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.DAL.Models.BankAccounts.CardBankAccount", b =>
                {
                    b.HasBaseType("Core.DAL.Models.Base.BaseBankAccount");

                    b.Property<Guid>("DebitCardId")
                        .HasColumnType("uuid");

                    b.ToTable("CardBankAccounts");
                });

            modelBuilder.Entity("Core.DAL.Models.BankAccounts.CreditBankAccount", b =>
                {
                    b.HasBaseType("Core.DAL.Models.Base.BaseBankAccount");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Debt")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PayingCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("CreditCardId")
                        .IsUnique();

                    b.HasIndex("PayingCardId")
                        .IsUnique();

                    b.HasIndex("TariffId");

                    b.ToTable("CreditBankAccounts");
                });

            modelBuilder.Entity("Core.DAL.Models.Cards.CreditCard", b =>
                {
                    b.HasBaseType("Core.DAL.Models.Base.Card");

                    b.Property<Guid>("CreditBankAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("Core.DAL.Models.Cards.DebitCard", b =>
                {
                    b.HasBaseType("Core.DAL.Models.Base.Card");

                    b.Property<Guid>("CardBankAccountId")
                        .HasColumnType("uuid");

                    b.HasIndex("CardBankAccountId")
                        .IsUnique();

                    b.ToTable("DebitCards");
                });

            modelBuilder.Entity("Core.DAL.Models.Base.BaseBankAccount", b =>
                {
                    b.HasOne("Core.DAL.Models.User", "Owner")
                        .WithMany("BankAccounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Core.DAL.Models.Base.Card", b =>
                {
                    b.HasOne("Core.DAL.Models.User", "Owner")
                        .WithMany("Cards")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Core.DAL.Models.History.BankAccountOperationsHistory", b =>
                {
                    b.HasOne("Core.DAL.Models.Base.BaseBankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.DAL.Models.BankAccounts.CardBankAccount", b =>
                {
                    b.HasOne("Core.DAL.Models.Base.BaseBankAccount", null)
                        .WithOne()
                        .HasForeignKey("Core.DAL.Models.BankAccounts.CardBankAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.DAL.Models.BankAccounts.CreditBankAccount", b =>
                {
                    b.HasOne("Core.DAL.Models.Cards.CreditCard", "CreditCard")
                        .WithOne("CreditBankAccount")
                        .HasForeignKey("Core.DAL.Models.BankAccounts.CreditBankAccount", "CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.DAL.Models.Base.BaseBankAccount", null)
                        .WithOne()
                        .HasForeignKey("Core.DAL.Models.BankAccounts.CreditBankAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.DAL.Models.Base.Card", "PayingCard")
                        .WithOne()
                        .HasForeignKey("Core.DAL.Models.BankAccounts.CreditBankAccount", "PayingCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.DAL.Models.BankAccounts.Tariff.CreditTariff", "Tariff")
                        .WithMany("CreditBankAccounts")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("PayingCard");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Core.DAL.Models.Cards.CreditCard", b =>
                {
                    b.HasOne("Core.DAL.Models.Base.Card", null)
                        .WithOne()
                        .HasForeignKey("Core.DAL.Models.Cards.CreditCard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.DAL.Models.Cards.DebitCard", b =>
                {
                    b.HasOne("Core.DAL.Models.BankAccounts.CardBankAccount", "CardBankAccount")
                        .WithOne("DebitCard")
                        .HasForeignKey("Core.DAL.Models.Cards.DebitCard", "CardBankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.DAL.Models.Base.Card", null)
                        .WithOne()
                        .HasForeignKey("Core.DAL.Models.Cards.DebitCard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardBankAccount");
                });

            modelBuilder.Entity("Core.DAL.Models.BankAccounts.Tariff.CreditTariff", b =>
                {
                    b.Navigation("CreditBankAccounts");
                });

            modelBuilder.Entity("Core.DAL.Models.User", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Core.DAL.Models.BankAccounts.CardBankAccount", b =>
                {
                    b.Navigation("DebitCard")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.DAL.Models.Cards.CreditCard", b =>
                {
                    b.Navigation("CreditBankAccount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
